### ISSUE TITLE
The compressed files in 'datasets_csv_mutsig' cannot be uncompressed.

### ISSUE THREAD

**Issue by DaIGaN2019** [mahmoodlab/PORPOISE#13]
Hello, author, thank you for your selfless sharing. I could not find the tcga-coadread file in the "datasets_csv" folder, but fortunately, I found it in "datasets_csv_mutsig". 1. Do these two folders contain the same type of files? 2. After downloading "datasets_csv_mutsig" to my local machine and unzipping it (with WinRAR), the compressed files inside could not be further uncompressed, displaying that the file format is unknown or damaged. Can you give me some advice? Thank you.

**Comment by codicef** [comment]
The files within the archive are labeled with the extension ".csv.zip," but they are not compressed; they are actually plain CSV files. Therefore, you should extract the contents of each dataset from the 'datasets_csv_mutig' archive once and then change the file extension from ".csv.zip" to ".csv."

**Comment by DaIGaN2019** [comment]
Thank you so much for the help you provided. Following your guidance, I processed the file and obtained the data I needed. Best wishes to you!
