### ISSUE TITLE
What is the Fusion method used in article？

### ISSUE THREAD

**Issue by Psilym** [mahmoodlab/PORPOISE#6]
Hello, 
In code, there are three fusion mode, i.e. 'concat', 'bilinear', 'lrb'. The research mentions that "a multimodal fusion layer that computes the Kronecker Product to model pairwise feature interactions between histology and molecular features". Thus, which is the exact fusion method used in paper?

**Comment by Richarizardd** [comment]
Hi @Psilym - "Bilinear" was used.
