### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by Qing1Zhong** [mahmoodlab/PORPOISE#7]
I noticed that your description of the selection of molecular feature is "**For RNA-Seq abundance, we selected the top 2000 genes with the largest median absolute deviation for inclusion**". Why were genes with larger median absolute deviation selected as SNN input? 
As far as I know, the larger the median absolute deviation in a set of data, the higher the probability that there are abnormal points in the set of data. In general, we should choose data with low median absolute deviation. I was hoping you could explain it to me. Thank you!

**Comment by Richarizardd** [comment]
Hi @Qing1Zhong - please see the latest version of the camera-ready version in Cancer Cell. The feature extraction was updated to no longer do median absolute deviation for feature selection, rather, gene sets from [MutSigDB](http://www.gsea-msigdb.org/gsea/msigdb/)

**Comment by Qing1Zhong** [comment]
Hi, @Richarizardd thanks a lot for your kind reply! So the rna-seq process is 
1. Download the raw data from **MutSigDB-C4-CGN(cancer gene neignborhoods, 427 gene sets)** and **cBioPortal**.
2. Compare the genes in the cBioPortal file(**data_mrna_seq_v2_rsem_zscores_ref_diploid_samples.txt**) with 427 gene sets. If these genes are included in 427 gene sets, they are adopted.
Is my understanding correct?
